insert into Person (firstName, lastName, age, address, gender) VALUES ('Anders', 'Anderson', 19, 'Anderssonsgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Bente', 'Bentson', 19, 'Bentesgate', 'female')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Carl', 'Carlson', 20, 'Carlsgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Didrik', 'Didrikson', 19, 'Didrikssgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Else', 'Elsesson', 20, 'Elsessgate', 'female')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Frida', 'Fridason', 21, 'Fridassgate', 'female')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Geir', 'Geirsson', 21, 'Geirssgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Hans', 'Hansson', 20, 'Hanssonsgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Inge', 'Ingson', 19, 'Ingesgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Jeanette', 'Jansen', 21, 'Jansensgate', 'female')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Knut', 'Knutson', 22, 'Knutsgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Lars', 'Larsson', 20, 'Larssgate', 'male')

insert into Person (firstName, lastName, age, address, gender) VALUES ('Markus', 'Anderson', 19, 'Anderssonsgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Nils', 'Bentson', 19, 'Bentesgate', 'female')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Oda', 'Carlson', 20, 'Carlsgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Per', 'Didrikson', 19, 'Didrikssgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Rita', 'Elsesson', 20, 'Elsessgate', 'female')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Stine', 'Fridason', 21, 'Fridassgate', 'female')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Truls', 'Geirsson', 21, 'Geirssgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Ulrik', 'Hansson', 20, 'Hanssonsgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Vegard', 'Ingson', 19, 'Ingesgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Will', 'Jansen', 21, 'Jansensgate', 'female')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Xin', 'Knutson', 22, 'Knutsgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Yngve', 'Larsson', 20, 'Larssgate', 'male')

insert into Person (firstName, lastName, age, address, gender) VALUES ('Anders', 'Anderson', 22, 'Anderssonsgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Bente', 'Bentson', 23, 'Bentesgate', 'female')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Carl', 'Carlson', 22, 'Carlsgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Didrik', 'Didrikson', 21, 'Didrikssgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Else', 'Elsesson', 30, 'Elsessgate', 'female')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Frida', 'Fridason', 22, 'Fridassgate', 'female')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Geir', 'Geirsson', 21, 'Geirssgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Hans', 'Hansson', 25, 'Hanssonsgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Inge', 'Ingson', 24, 'Ingesgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Jeanette', 'Jansen', 23, 'Jansensgate', 'female')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Knut', 'Knutson', 22, 'Knutsgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Lars', 'Larsson', 23, 'Larssgate', 'male')

insert into Person (firstName, lastName, age, address, gender) VALUES ('Markus', 'Anderson', 19, 'Anderssonsgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Nils', 'Bentson', 19, 'Bentesgate', 'female')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Oda', 'Carlson', 20, 'Carlsgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Per', 'Didrikson', 19, 'Didrikssgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Rita', 'Elsesson', 20, 'Elsessgate', 'female')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Stine', 'Fridason', 21, 'Fridassgate', 'female')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Truls', 'Geirsson', 21, 'Geirssgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Ulrik', 'Hansson', 20, 'Hanssonsgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Vegard', 'Ingson', 19, 'Ingesgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Will', 'Jansen', 21, 'Jansensgate', 'female')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Xin', 'Knutson', 22, 'Knutsgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Yngve', 'Larsson', 20, 'Larssgate', 'male')

insert into Person (firstName, lastName, age, address, gender) VALUES ('Anders', 'Anderson', 19, 'Anderssonsgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Bente', 'Bentson', 19, 'Bentesgate', 'female')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Carl', 'Carlson', 20, 'Carlsgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Didrik', 'Didrikson', 19, 'Didrikssgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Else', 'Elsesson', 20, 'Elsessgate', 'female')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Frida', 'Fridason', 21, 'Fridassgate', 'female')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Geir', 'Geirsson', 21, 'Geirssgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Hans', 'Hansson', 20, 'Hanssonsgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Inge', 'Ingson', 19, 'Ingesgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Jeanette', 'Jansen', 21, 'Jansensgate', 'female')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Knut', 'Knutson', 22, 'Knutsgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Lars', 'Larsson', 20, 'Larssgate', 'male')

insert into Person (firstName, lastName, age, address, gender) VALUES ('Markus', 'Anderson', 19, 'Anderssonsgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Nils', 'Bentson', 19, 'Bentesgate', 'female')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Oda', 'Carlson', 20, 'Carlsgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Per', 'Didrikson', 19, 'Didrikssgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Rita', 'Elsesson', 20, 'Elsessgate', 'female')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Stine', 'Fridason', 21, 'Fridassgate', 'female')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Truls', 'Geirsson', 21, 'Geirssgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Ulrik', 'Hansson', 20, 'Hanssonsgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Vegard', 'Ingson', 19, 'Ingesgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Will', 'Jansen', 21, 'Jansensgate', 'female')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Xin', 'Knutson', 22, 'Knutsgate', 'male')
insert into Person (firstName, lastName, age, address, gender) VALUES ('Yngve', 'Larsson', 20, 'Larssgate', 'male')



